# nixpacks設定ファイル
# Node.jsとPythonの両方を使用

[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
    "npm install",
    "python -m pip install --upgrade pip",
    "python -m pip install -r python-scripts/requirements.txt"
]

[start]
cmd = "npm run start"